// worker-template/src/types.ts
//
// Shared protocol types — single source of truth for the worker side.
// Mirrors extension/lib/protocol.js and python-template/onboard_common/protocol.py.
//
// Keep these in sync. When adding a new command type, update ALL THREE files.

export const PROTOCOL_VERSION = "1.0";

export const CMD = {
  PING: "ping",
  FETCH: "fetch",
  PAGE_FETCH: "page.fetch",
  TABS_OPEN: "tabs.open",
  TABS_CLOSE: "tabs.close",
  TABS_LIST: "tabs.list",
  TABS_FOCUS: "tabs.focus",
  FORM_FILL: "form.fill",
  FORM_CLICK: "form.click",
  FORM_WAIT: "form.wait",
  FORM_EVAL: "form.eval",
  XHR_INTERCEPT: "xhr.intercept",
  COOKIES_GET: "cookies.get",
  COOKIES_GET_ALL: "cookies.getAll",
  COOKIES_SET: "cookies.set",
  SCREENSHOT: "screenshot",
  CAPTCHA_GET_TOKEN: "captcha.getToken",
  SANDBOX_OPEN: "sandbox.open",
  SANDBOX_FETCH: "sandbox.fetch",
  DEBUG_HAR_START: "debug.har.start",
  DEBUG_HAR_STOP: "debug.har.stop",
  DEBUG_CONSOLE_START: "debug.console.start",
  DEBUG_CONSOLE_STOP: "debug.console.stop",
  DEBUG_NETWORK_START: "debug.network.start",
  DEBUG_NETWORK_STOP: "debug.network.stop",
  DEBUG_TRACE_START: "debug.trace.start",
  DEBUG_TRACE_STOP: "debug.trace.stop",
  DEBUG_DOM_SNAPSHOT: "debug.dom.snapshot",
  DEBUG_STORAGE_DUMP: "debug.storage.dump",
  DEBUG_SCREENSHOT_FULL: "debug.screenshot.fullpage",
} as const;

export type CommandType = typeof CMD[keyof typeof CMD];

export const MSG = {
  AUTH: "auth",
  CONNECT: "connect",
  AUTH_OK: "auth-ok",
  RESULT: "result",
  LOG: "log",
  PONG: "pong",
  EVENT: "event",
  STATUS: "status",
} as const;

export const CONTEXT = {
  WORKER: "worker",
  PAGE: "page",
} as const;

export type Context = typeof CONTEXT[keyof typeof CONTEXT];

/** Server -> Extension. The id is generated by the server (DO or daemon). */
export interface Command<T extends CommandType = CommandType> {
  type: T;
  id: string;
  protocolVersion?: string;
  traceId?: string;
  timeoutMs?: number;
  // Payload fields vary by type — see extension/lib/protocol.js for the full list
  [key: string]: unknown;
}

/** Extension -> Server. Result envelope for a command. */
export interface Result {
  type: typeof MSG.RESULT;
  id: string;
  ok: boolean;
  traceId?: string | null;
  durationMs?: number | null;
  error?: string;
  // Result fields vary by command type
  [key: string]: unknown;
}

/** Extension -> Server. Async event from an activatable debug stream. */
export interface Event {
  type: typeof MSG.EVENT;
  event: string;
  tabId: number | null;
  sessionId: string | null;
  traceId?: string | null;
  ts: number;
  data: unknown;
}

/** Extension -> Server. Structured log entry. */
export interface LogEntry {
  type: typeof MSG.LOG;
  ts: number;
  level: "debug" | "info" | "warn" | "error";
  message: string;
  data?: Record<string, unknown>;
  agentId: string;
  commandId?: string | null;
  tabId?: number | null;
  durationMs?: number | null;
  traceId?: string | null;
}

/** Extension -> Server. Sent immediately on WS open. */
export interface AuthMessage {
  type: typeof MSG.AUTH;
  token: string;
}

/** Extension -> Server. Sent after auth-ok. Announces identity + capabilities. */
export interface ConnectMessage {
  type: typeof MSG.CONNECT;
  agentId: string;
  protocolVersion: string;
  capabilities: string[];
  context: Context;
  userAgent: string;
  hostname: string;
}

export type ExtensionMessage = AuthMessage | ConnectMessage | Result | Event | LogEntry | { type: "pong"; ts: number };

/** Connection record stored in the BridgeHub DO. */
export interface ExtensionConnection {
  ws: WebSocket;
  connId: string;
  agentId: string;
  context: Context;
  protocolVersion: string;
  capabilities: string[];
  authenticated: boolean;
  commandCount: number;
  lastSeen: number;
}

/** Pending command waiting for a result. */
export interface PendingCommand {
  resolve: (r: Result) => void;
  reject: (e: Error) => void;
  timer: ReturnType<typeof setTimeout>;
  type: CommandType;
  startedAt: number;
  connId?: string;
  traceId?: string;
}

export interface Env {
  BRIDGE_TOKEN: string;
  BRIDGE_NO_AUTH?: string;  // "1" to disable auth
  DB?: D1Database;
  BRIDGE_HUB: DurableObjectNamespace;
}
